import { sqliteTable, text, integer, real } from "drizzle-orm/sqlite-core";

// Agent sessions — each time user connects to an AI coding agent
export const agentSessions = sqliteTable("agent_sessions", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  agentType: text("agent_type").notNull(), // "claude-code" | "opencode" | "codex"
  model: text("model").notNull(),
  status: text("status").notNull().default("active"), // "active" | "idle" | "ended"
  cloudUrl: text("cloud_url"), // if running in cloud (Runable sandbox URL)
  totalInputTokens: integer("total_input_tokens").notNull().default(0),
  totalOutputTokens: integer("total_output_tokens").notNull().default(0),
  totalCacheReadTokens: integer("total_cache_read_tokens").notNull().default(0),
  totalCacheWriteTokens: integer("total_cache_write_tokens").notNull().default(0),
  totalCostUsd: real("total_cost_usd").notNull().default(0),
  optimizationScore: integer("optimization_score"), // 0-100, nullable
  createdAt: integer("created_at", { mode: "timestamp" })
    .notNull()
    .$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" })
    .notNull()
    .$defaultFn(() => new Date()),
});

// Individual token events — each AI message/response with token counts
export const tokenEvents = sqliteTable("token_events", {
  id: text("id").primaryKey(),
  sessionId: text("session_id").notNull().references(() => agentSessions.id),
  role: text("role").notNull(), // "user" | "assistant"
  inputTokens: integer("input_tokens").notNull().default(0),
  outputTokens: integer("output_tokens").notNull().default(0),
  cacheReadTokens: integer("cache_read_tokens").notNull().default(0),
  cacheWriteTokens: integer("cache_write_tokens").notNull().default(0),
  costUsd: real("cost_usd").notNull().default(0),
  model: text("model").notNull(),
  prompt: text("prompt"), // truncated user prompt
  createdAt: integer("created_at", { mode: "timestamp" })
    .notNull()
    .$defaultFn(() => new Date()),
});

// Optimization tips generated by AI
export const optimizationTips = sqliteTable("optimization_tips", {
  id: text("id").primaryKey(),
  sessionId: text("session_id").notNull().references(() => agentSessions.id),
  tip: text("tip").notNull(),
  category: text("category").notNull(), // "caching" | "context" | "model" | "prompting"
  estimatedSavingPct: integer("estimated_saving_pct").notNull().default(0),
  applied: integer("applied", { mode: "boolean" }).notNull().default(false),
  createdAt: integer("created_at", { mode: "timestamp" })
    .notNull()
    .$defaultFn(() => new Date()),
});

// Model pricing table — used for cost calculation
export const modelPricing = sqliteTable("model_pricing", {
  id: text("id").primaryKey(),
  modelId: text("model_id").notNull().unique(),
  provider: text("provider").notNull(),
  displayName: text("display_name").notNull(),
  inputCostPer1M: real("input_cost_per_1m").notNull(), // USD per 1M input tokens
  outputCostPer_1M: real("output_cost_per_1m").notNull(), // USD per 1M output tokens
  cacheReadCostPer1M: real("cache_read_cost_per_1m").notNull().default(0),
  cacheWriteCostPer1M: real("cache_write_cost_per_1m").notNull().default(0),
  updatedAt: integer("updated_at", { mode: "timestamp" })
    .notNull()
    .$defaultFn(() => new Date()),
});
